from db_manager import JSONDatabase


def seed_data():
    db = JSONDatabase()

    db.seed("users", [
        {"id": "instr01", "name": "Dr. Ayesha Khan", "email": "ayesha@atomcamp.com", "role": "instructor",
         "goal": "Teach", "skill_level": "expert", "background": "PhD Computer Science",
         "time_commitment": 40, "created_at": "2026-01-01T09:00:00", "last_login": "2026-05-13T08:00:00"},
        {"id": "instr02", "name": "Bilal Ahmed", "email": "bilal@atomcamp.com", "role": "instructor",
         "goal": "Teach", "skill_level": "expert", "background": "Ex-Google PM",
         "time_commitment": 30, "created_at": "2026-01-01T09:00:00", "last_login": "2026-05-12T10:00:00"},
        {"id": "stu01", "name": "Hassan Raza", "email": "hassan@demo.com", "role": "student",
         "goal": "Data Science", "skill_level": "intermediate", "background": "Switching careers",
         "time_commitment": 15, "created_at": "2026-03-01T10:00:00", "last_login": "2026-05-13T08:00:00"},
        {"id": "stu02", "name": "Fatima Ali", "email": "fatima@demo.com", "role": "student",
         "goal": "AI", "skill_level": "intermediate", "background": "Upskilling",
         "time_commitment": 20, "created_at": "2026-03-05T11:00:00", "last_login": "2026-05-12T19:00:00"},
        {"id": "stu03", "name": "Omar Sheikh", "email": "omar@demo.com", "role": "student",
         "goal": "Web Development", "skill_level": "beginner", "background": "Student",
         "time_commitment": 10, "created_at": "2026-03-10T09:30:00", "last_login": "2026-04-20T14:00:00"},
        {"id": "stu04", "name": "Mariam Iqbal", "email": "mariam@demo.com", "role": "student",
         "goal": "Marketing", "skill_level": "beginner", "background": "Fresh graduate",
         "time_commitment": 12, "created_at": "2026-03-15T16:00:00", "last_login": "2026-05-13T07:00:00"},
        {"id": "stu05", "name": "Zain Malik", "email": "zain@demo.com", "role": "student",
         "goal": "Product", "skill_level": "advanced", "background": "Founder",
         "time_commitment": 8, "created_at": "2026-03-20T13:00:00", "last_login": "2026-05-11T20:00:00"},
        {"id": "stu06", "name": "Ayesha Tariq", "email": "ayesha.t@demo.com", "role": "student",
         "goal": "Analytics", "skill_level": "intermediate", "background": "Switching careers",
         "time_commitment": 18, "created_at": "2026-03-25T08:00:00", "last_login": "2026-05-13T09:30:00"},
        {"id": "stu07", "name": "Bilal Khan", "email": "bilal.k@demo.com", "role": "student",
         "goal": "Data Science", "skill_level": "beginner", "background": "Student",
         "time_commitment": 7, "created_at": "2026-04-01T12:00:00", "last_login": "2026-04-15T11:00:00"},
        {"id": "stu08", "name": "Sana Javed", "email": "sana@demo.com", "role": "student",
         "goal": "AI", "skill_level": "intermediate", "background": "Upskilling",
         "time_commitment": 14, "created_at": "2026-04-05T09:00:00", "last_login": "2026-05-12T22:00:00"},
    ])

    db.seed("enrollments", [
        {"id": "e01", "user_id": "stu01", "course_id": "c_ds", "enrolled_at": "2026-03-01T10:05:00"},
        {"id": "e02", "user_id": "stu02", "course_id": "c_genai", "enrolled_at": "2026-03-05T11:05:00"},
        {"id": "e03", "user_id": "stu03", "course_id": "c_web", "enrolled_at": "2026-03-10T09:35:00"},
        {"id": "e04", "user_id": "stu04", "course_id": "c_dm", "enrolled_at": "2026-03-15T16:05:00"},
        {"id": "e05", "user_id": "stu05", "course_id": "c_pm", "enrolled_at": "2026-03-20T13:05:00"},
        {"id": "e06", "user_id": "stu06", "course_id": "c_da", "enrolled_at": "2026-03-25T08:05:00"},
        {"id": "e07", "user_id": "stu07", "course_id": "c_ds", "enrolled_at": "2026-04-01T12:05:00"},
        {"id": "e08", "user_id": "stu08", "course_id": "c_genai", "enrolled_at": "2026-04-05T09:05:00"},
        {"id": "e09", "user_id": "stu02", "course_id": "c_ds", "enrolled_at": "2026-04-10T10:00:00"},
    ])

    db.seed("progress", [
        {"id": "p01", "user_id": "stu01", "module_id": "m_ds_py", "last_score": 92, "status": "completed", "attempts": 1, "updated_at": "2026-03-10T10:00:00"},
        {"id": "p02", "user_id": "stu01", "module_id": "m_ds_pandas", "last_score": 88, "status": "completed", "attempts": 1, "updated_at": "2026-03-20T10:00:00"},
        {"id": "p03", "user_id": "stu01", "module_id": "m_ds_stats", "last_score": 76, "status": "completed", "attempts": 2, "updated_at": "2026-04-15T10:00:00"},
        {"id": "p04", "user_id": "stu02", "module_id": "m_ai_llm", "last_score": 96, "status": "completed", "attempts": 1, "updated_at": "2026-03-15T10:00:00"},
        {"id": "p05", "user_id": "stu02", "module_id": "m_ai_prompt", "last_score": 92, "status": "completed", "attempts": 1, "updated_at": "2026-03-25T10:00:00"},
        {"id": "p06", "user_id": "stu02", "module_id": "m_ai_embed", "last_score": 84, "status": "completed", "attempts": 1, "updated_at": "2026-04-10T10:00:00"},
        {"id": "p07", "user_id": "stu03", "module_id": "m_web_html", "last_score": 80, "status": "completed", "attempts": 1, "updated_at": "2026-03-20T10:00:00"},
        {"id": "p08", "user_id": "stu03", "module_id": "m_web_css", "last_score": 40, "status": "needs_review", "attempts": 3, "updated_at": "2026-04-05T10:00:00"},
        {"id": "p09", "user_id": "stu04", "module_id": "m_dm_intro", "last_score": 84, "status": "completed", "attempts": 1, "updated_at": "2026-03-25T10:00:00"},
        {"id": "p10", "user_id": "stu04", "module_id": "m_dm_seo", "last_score": 72, "status": "completed", "attempts": 1, "updated_at": "2026-04-10T10:00:00"},
        {"id": "p11", "user_id": "stu05", "module_id": "m_pm_think", "last_score": 96, "status": "completed", "attempts": 1, "updated_at": "2026-04-01T10:00:00"},
        {"id": "p12", "user_id": "stu05", "module_id": "m_pm_research", "last_score": 92, "status": "completed", "attempts": 1, "updated_at": "2026-04-12T10:00:00"},
        {"id": "p13", "user_id": "stu05", "module_id": "m_pm_road", "last_score": 88, "status": "completed", "attempts": 1, "updated_at": "2026-04-25T10:00:00"},
        {"id": "p14", "user_id": "stu06", "module_id": "m_da_excel", "last_score": 100, "status": "completed", "attempts": 1, "updated_at": "2026-04-01T10:00:00"},
        {"id": "p15", "user_id": "stu06", "module_id": "m_da_sql1", "last_score": 92, "status": "completed", "attempts": 1, "updated_at": "2026-04-15T10:00:00"},
        {"id": "p16", "user_id": "stu06", "module_id": "m_da_sql2", "last_score": 84, "status": "completed", "attempts": 1, "updated_at": "2026-05-01T10:00:00"},
        {"id": "p17", "user_id": "stu07", "module_id": "m_ds_py", "last_score": 48, "status": "needs_review", "attempts": 3, "updated_at": "2026-04-12T10:00:00"},
        {"id": "p18", "user_id": "stu08", "module_id": "m_ai_llm", "last_score": 76, "status": "completed", "attempts": 2, "updated_at": "2026-04-20T10:00:00"},
        {"id": "p19", "user_id": "stu08", "module_id": "m_ai_prompt", "last_score": 56, "status": "needs_review", "attempts": 2, "updated_at": "2026-05-08T10:00:00"},
    ])

    courses = [
        {"id": "c_ds", "title": "Data Science Bootcamp", "track": "Data Science",
         "level": "Beginner to Intermediate", "duration_weeks": 12,
         "description": "Master the full data science workflow — Python, statistics, machine learning, and deep learning — through projects mapped to industry roles.",
         "outcomes": ["Build production-grade ML pipelines", "Communicate insights to non-technical stakeholders", "Pass technical interviews for analyst and DS roles"],
         "instructor_id": "instr01"},
        {"id": "c_genai", "title": "Generative AI Bootcamp", "track": "AI",
         "level": "Intermediate", "duration_weeks": 8,
         "description": "Go from prompt basics to shipping production LLM applications — RAG, agents, evaluation, and guardrails.",
         "outcomes": ["Architect retrieval-augmented systems", "Design tool-using agents", "Evaluate LLM apps systematically"],
         "instructor_id": "instr01"},
        {"id": "c_web", "title": "Full-Stack Web Development", "track": "Web Development",
         "level": "Beginner to Intermediate", "duration_weeks": 14,
         "description": "Build, deploy, and secure modern web applications using HTML, CSS, JavaScript, Flask, and REST best practices.",
         "outcomes": ["Ship a deployed full-stack project", "Design REST APIs that don't break", "Implement secure authentication"],
         "instructor_id": "instr02"},
        {"id": "c_dm", "title": "Digital Marketing", "track": "Marketing",
         "level": "Beginner", "duration_weeks": 10,
         "description": "Data-driven marketing across SEO, content, paid media, and analytics — focused on measurable outcomes, not vanity metrics.",
         "outcomes": ["Run profitable paid campaigns", "Build organic growth engines", "Attribute revenue across channels"],
         "instructor_id": "instr02"},
        {"id": "c_pm", "title": "Product Management", "track": "Product",
         "level": "Intermediate", "duration_weeks": 10,
         "description": "Discover, define, and deliver products users love — frameworks for research, prioritization, metrics, and experimentation.",
         "outcomes": ["Write rigorous PRDs and acceptance criteria", "Design and read A/B tests", "Align stakeholders around a roadmap"],
         "instructor_id": "instr01"},
        {"id": "c_da", "title": "Data Analytics", "track": "Analytics",
         "level": "Beginner to Intermediate", "duration_weeks": 10,
         "description": "From spreadsheets to advanced SQL, BI tools, and storytelling — the toolkit for translating data into business decisions.",
         "outcomes": ["Write production-grade SQL", "Build executive dashboards", "Run defensible A/B tests"],
         "instructor_id": "instr02"},
    ]
    db.seed("courses", courses)

    modules = [
        # Data Science
        {"id": "m_ds_py", "course_id": "c_ds", "order": 1, "title": "Python Foundations",
         "duration_minutes": 240, "advanced_id": None,
         "content": "Variables, data types, control flow, functions, comprehensions, and object-oriented programming. Build a fluent foundation in idiomatic Python — the language used across the data stack.",
         "objectives": ["Write Pythonic code using comprehensions and unpacking", "Apply OOP for reusable data tooling", "Reason about mutability and references"]},
        {"id": "m_ds_pandas", "course_id": "c_ds", "order": 2, "title": "NumPy & Pandas",
         "duration_minutes": 300, "advanced_id": None,
         "content": "Vectorized computation with NumPy, tabular manipulation with Pandas — joins, groupby, reshaping, and time series. The workhorses of every data role.",
         "objectives": ["Replace Python loops with vectorized operations", "Master joins, groupby, and pivoting", "Diagnose SettingWithCopyWarning"]},
        {"id": "m_ds_viz", "course_id": "c_ds", "order": 3, "title": "Data Visualization",
         "duration_minutes": 180, "advanced_id": None,
         "content": "Matplotlib, Seaborn, and Plotly for analytical and presentation-grade charts. Principles of visual encoding, accessibility, and storytelling.",
         "objectives": ["Choose the right chart for the question", "Apply pre-attentive attributes intentionally", "Build dashboards that drive decisions"]},
        {"id": "m_ds_stats", "course_id": "c_ds", "order": 4, "title": "Statistics & Probability",
         "duration_minutes": 360, "advanced_id": None,
         "content": "Distributions, sampling, hypothesis testing, confidence intervals, and the Central Limit Theorem. The statistical literacy that separates analysts from spreadsheet operators.",
         "objectives": ["Interpret p-values without overclaiming", "Design tests with sufficient power", "Avoid common inferential errors"]},
        {"id": "m_ds_ml", "course_id": "c_ds", "order": 5, "title": "Machine Learning Fundamentals",
         "duration_minutes": 420, "advanced_id": None,
         "content": "Supervised vs unsupervised learning, the bias-variance tradeoff, regularization, and the scikit-learn workflow. Train, evaluate, and tune real models.",
         "objectives": ["Frame business problems as ML problems", "Apply regularization and feature engineering", "Diagnose under- and overfitting"]},
        {"id": "m_ds_eval", "course_id": "c_ds", "order": 6, "title": "Model Evaluation",
         "duration_minutes": 240, "advanced_id": None,
         "content": "Cross-validation, classification metrics, ROC and PR curves, calibration, and pitfalls of accuracy. How to know your model actually works.",
         "objectives": ["Select metrics aligned to business cost", "Detect data leakage", "Calibrate probabilistic predictions"]},
        {"id": "m_ds_dl", "course_id": "c_ds", "order": 7, "title": "Deep Learning Intro",
         "duration_minutes": 360, "advanced_id": None,
         "content": "Neural network mechanics, backpropagation, activation functions, and the modern training loop with PyTorch.",
         "objectives": ["Implement and train a feedforward network", "Reason about vanishing/exploding gradients", "Apply transfer learning"]},

        # Generative AI
        {"id": "m_ai_llm", "course_id": "c_genai", "order": 1, "title": "LLM Fundamentals",
         "duration_minutes": 240, "advanced_id": None,
         "content": "Transformer architecture, attention, tokenization, and scaling laws. Build the mental model behind how modern LLMs actually work.",
         "objectives": ["Explain attention from first principles", "Reason about context windows and KV caching", "Interpret sampling parameters"]},
        {"id": "m_ai_prompt", "course_id": "c_genai", "order": 2, "title": "Prompt Engineering",
         "duration_minutes": 180, "advanced_id": None,
         "content": "System prompts, few-shot patterns, chain-of-thought, structured outputs, and the empirical art of getting reliable behavior from LLMs.",
         "objectives": ["Design prompts that generalize", "Force structured outputs reliably", "Defend against prompt injection"]},
        {"id": "m_ai_embed", "course_id": "c_genai", "order": 3, "title": "Embeddings & Vector Search",
         "duration_minutes": 240, "advanced_id": None,
         "content": "Embedding models, similarity metrics, approximate nearest neighbor indexes, and hybrid search. The retrieval substrate behind every RAG system.",
         "objectives": ["Choose between dot product, cosine, and L2", "Build hybrid search with BM25 + vectors", "Evaluate retrieval quality"]},
        {"id": "m_ai_rag", "course_id": "c_genai", "order": 4, "title": "Retrieval-Augmented Generation",
         "duration_minutes": 300, "advanced_id": None,
         "content": "Chunking strategies, retrieval pipelines, re-ranking, and grounding. Move from demo to production-grade RAG.",
         "objectives": ["Design chunking strategies for your domain", "Apply re-ranking and query rewriting", "Diagnose retrieval failures"]},
        {"id": "m_ai_tools", "course_id": "c_genai", "order": 5, "title": "Function Calling & Tool Use",
         "duration_minutes": 240, "advanced_id": None,
         "content": "JSON schemas, tool definitions, multi-turn tool loops, and parallel calls. Turn an LLM into a reasoning interface to your systems.",
         "objectives": ["Define tools that the model uses correctly", "Handle tool errors and retries", "Run parallel tool calls"]},
        {"id": "m_ai_agents", "course_id": "c_genai", "order": 6, "title": "AI Agents",
         "duration_minutes": 300, "advanced_id": None,
         "content": "Planning, memory, reflection, and multi-step autonomous workflows. ReAct, plan-and-execute, and when not to use agents.",
         "objectives": ["Decide between workflow vs agent", "Add short- and long-term memory", "Bound cost and runaway loops"]},
        {"id": "m_ai_eval", "course_id": "c_genai", "order": 7, "title": "Evaluation & Guardrails",
         "duration_minutes": 240, "advanced_id": None,
         "content": "Golden datasets, regression tests, LLM-as-judge, and runtime guardrails. The discipline that turns prototypes into reliable products.",
         "objectives": ["Build an evaluation harness", "Run LLM-as-judge responsibly", "Layer input/output guardrails"]},

        # Web Development
        {"id": "m_web_html", "course_id": "c_web", "order": 1, "title": "HTML & Semantic Markup",
         "duration_minutes": 180, "advanced_id": None,
         "content": "Semantic elements, accessibility, ARIA, and the document outline. Build markup that works for screen readers, SEO, and humans.",
         "objectives": ["Write semantic HTML5", "Apply ARIA where native semantics fall short", "Pass a Lighthouse accessibility audit"]},
        {"id": "m_web_css", "course_id": "c_web", "order": 2, "title": "Modern CSS",
         "duration_minutes": 240, "advanced_id": None,
         "content": "Flexbox, Grid, custom properties, container queries, and responsive design. The modern layout toolkit without the cargo-cult.",
         "objectives": ["Choose Flexbox vs Grid intentionally", "Build with custom properties and design tokens", "Handle responsive layouts without media-query soup"]},
        {"id": "m_web_js", "course_id": "c_web", "order": 3, "title": "JavaScript Essentials",
         "duration_minutes": 300, "advanced_id": None,
         "content": "Closures, async/await, ES modules, and the event loop. The mechanics every web developer needs in their fingertips.",
         "objectives": ["Reason about scope and closure", "Use async/await without race conditions", "Explain the event loop and microtask queue"]},
        {"id": "m_web_dom", "course_id": "c_web", "order": 4, "title": "DOM & Browser APIs",
         "duration_minutes": 240, "advanced_id": None,
         "content": "Event delegation, fetch, IntersectionObserver, storage APIs, and performance APIs. The browser as a platform.",
         "objectives": ["Use event delegation for performance", "Debounce and throttle correctly", "Pick the right storage API"]},
        {"id": "m_web_flask", "course_id": "c_web", "order": 5, "title": "Flask Backend",
         "duration_minutes": 300, "advanced_id": None,
         "content": "Routing, blueprints, request context, templating with Jinja, and persistence with SQLAlchemy. The backend half of the stack.",
         "objectives": ["Organize Flask apps with blueprints", "Handle requests safely (sessions, CSRF, errors)", "Persist with SQLAlchemy without N+1 queries"]},
        {"id": "m_web_rest", "course_id": "c_web", "order": 6, "title": "REST API Design",
         "duration_minutes": 240, "advanced_id": None,
         "content": "HTTP semantics, status codes, idempotency, versioning, pagination, and error envelopes. Design APIs that survive contact with clients.",
         "objectives": ["Apply HTTP methods correctly", "Version APIs without breaking clients", "Design consistent error responses"]},
        {"id": "m_web_auth", "course_id": "c_web", "order": 7, "title": "Authentication & Security",
         "duration_minutes": 300, "advanced_id": None,
         "content": "Sessions vs tokens, OAuth 2.0, OWASP Top 10, and password storage. Don't roll your own crypto — but know what you're using.",
         "objectives": ["Implement secure session-based auth", "Use OAuth 2.0 / PKCE correctly", "Defend against the OWASP Top 10"]},

        # Digital Marketing
        {"id": "m_dm_intro", "course_id": "c_dm", "order": 1, "title": "Marketing Fundamentals",
         "duration_minutes": 180, "advanced_id": None,
         "content": "The marketing funnel, AIDA, customer journey mapping, and unit economics. The vocabulary every marketer must own.",
         "objectives": ["Map a full-funnel customer journey", "Reason about CAC and LTV", "Distinguish brand vs performance objectives"]},
        {"id": "m_dm_seo", "course_id": "c_dm", "order": 2, "title": "Search Engine Optimization",
         "duration_minutes": 240, "advanced_id": None,
         "content": "On-page, off-page, technical SEO, Core Web Vitals, and EEAT. The fundamentals of organic search visibility in 2026.",
         "objectives": ["Run an SEO site audit", "Optimize Core Web Vitals", "Build link-worthy content"]},
        {"id": "m_dm_content", "course_id": "c_dm", "order": 3, "title": "Content Marketing",
         "duration_minutes": 180, "advanced_id": None,
         "content": "Pillar pages, topic clusters, the skyscraper technique, and content distribution. Content that ranks, converts, and scales.",
         "objectives": ["Design pillar–cluster content architectures", "Repurpose content across channels", "Audit and prune content portfolios"]},
        {"id": "m_dm_paid", "course_id": "c_dm", "order": 4, "title": "Paid Advertising",
         "duration_minutes": 300, "advanced_id": None,
         "content": "Google Ads, Meta Ads, attribution, ROAS, and bid strategies. Profitable paid media is engineered, not stumbled into.",
         "objectives": ["Structure Google Ads accounts that scale", "Choose bid strategies by objective", "Diagnose Quality Score issues"]},
        {"id": "m_dm_social", "course_id": "c_dm", "order": 5, "title": "Social Media Strategy",
         "duration_minutes": 180, "advanced_id": None,
         "content": "Platform mechanics, the algorithm game, creator economy, and community building. Beyond posting and hoping.",
         "objectives": ["Pick channels using ICP-driven logic", "Optimize for platform-native formats", "Measure social ROI rigorously"]},
        {"id": "m_dm_email", "course_id": "c_dm", "order": 6, "title": "Email Marketing",
         "duration_minutes": 180, "advanced_id": None,
         "content": "List building, segmentation, deliverability, and lifecycle automations. Still the highest-ROI channel — when done right.",
         "objectives": ["Design lifecycle automation flows", "Manage deliverability and reputation", "Move beyond open-rate vanity metrics"]},
        {"id": "m_dm_analytics", "course_id": "c_dm", "order": 7, "title": "Marketing Analytics",
         "duration_minutes": 240, "advanced_id": None,
         "content": "GA4, UTMs, attribution models, and incrementality testing. Move from clicks-and-impressions to incremental revenue.",
         "objectives": ["Instrument GA4 with event-based tracking", "Compare attribution models honestly", "Design incrementality tests"]},

        # Product Management
        {"id": "m_pm_think", "course_id": "c_pm", "order": 1, "title": "Product Thinking",
         "duration_minutes": 180, "advanced_id": None,
         "content": "Jobs-to-be-done, opportunity sizing, and outcome-over-output thinking. The mental models that separate PMs from project managers.",
         "objectives": ["Frame problems using JTBD", "Size opportunities defensibly", "Distinguish outcomes from outputs"]},
        {"id": "m_pm_research", "course_id": "c_pm", "order": 2, "title": "User Research",
         "duration_minutes": 240, "advanced_id": None,
         "content": "Interviews, surveys, usability testing, and synthesis. Generate insight that survives leadership scrutiny.",
         "objectives": ["Run interviews that uncover real needs", "Design surveys that don't lie", "Synthesize qualitative data rigorously"]},
        {"id": "m_pm_road", "course_id": "c_pm", "order": 3, "title": "Roadmapping & Prioritization",
         "duration_minutes": 180, "advanced_id": None,
         "content": "RICE, MoSCoW, Kano, now-next-later, and stakeholder alignment. Frameworks that make trade-offs explicit.",
         "objectives": ["Apply RICE under uncertainty", "Build now-next-later roadmaps", "Align stakeholders without compromise paralysis"]},
        {"id": "m_pm_prd", "course_id": "c_pm", "order": 4, "title": "Requirements & PRDs",
         "duration_minutes": 240, "advanced_id": None,
         "content": "User stories, acceptance criteria in Given-When-Then, and non-functional requirements. Specs engineers can build from.",
         "objectives": ["Write user stories with INVEST criteria", "Author testable acceptance criteria", "Capture non-functional requirements"]},
        {"id": "m_pm_metrics", "course_id": "c_pm", "order": 5, "title": "Product Metrics",
         "duration_minutes": 180, "advanced_id": None,
         "content": "AARRR, North Star Metric, leading vs lagging indicators, and the trap of vanity metrics.",
         "objectives": ["Define a defensible North Star", "Distinguish leading from lagging metrics", "Avoid vanity metric traps"]},
        {"id": "m_pm_exp", "course_id": "c_pm", "order": 6, "title": "Experimentation",
         "duration_minutes": 240, "advanced_id": None,
         "content": "A/B test design, MDE, power, multiple testing, and reading results honestly. Where most PM-led tests go wrong — and how not to.",
         "objectives": ["Design tests with adequate power", "Avoid peeking and multiple-testing traps", "Read results without overclaiming"]},
        {"id": "m_pm_launch", "course_id": "c_pm", "order": 7, "title": "Launch & GTM",
         "duration_minutes": 180, "advanced_id": None,
         "content": "Positioning, beta strategies, launch tiers, and rollout safety. Launches that move the needle, not just the press release.",
         "objectives": ["Write a positioning statement that focuses execution", "Choose launch tiers by risk", "Run safe rollouts with feature flags"]},

        # Data Analytics
        {"id": "m_da_excel", "course_id": "c_da", "order": 1, "title": "Excel for Analytics",
         "duration_minutes": 180, "advanced_id": None,
         "content": "Formulas, lookups, pivot tables, and Power Query. The analytics tool that's still on every business user's desktop.",
         "objectives": ["Replace VLOOKUP with INDEX-MATCH / XLOOKUP", "Build pivot tables for ad-hoc analysis", "Shape data with Power Query"]},
        {"id": "m_da_sql1", "course_id": "c_da", "order": 2, "title": "SQL Fundamentals",
         "duration_minutes": 300, "advanced_id": "m_da_sql2",
         "content": "SELECT, JOINs, GROUP BY, subqueries, and the SQL execution order. The lingua franca of data analytics.",
         "objectives": ["Write correct multi-table queries", "Reason about JOIN cardinality", "Avoid NULL-handling pitfalls"]},
        {"id": "m_da_sql2", "course_id": "c_da", "order": 3, "title": "SQL Advanced",
         "duration_minutes": 300, "advanced_id": None,
         "content": "Window functions, CTEs, recursive queries, query optimization, and EXPLAIN. Where junior SQL becomes senior SQL.",
         "objectives": ["Apply window functions to ranking and time-series problems", "Refactor with CTEs", "Read query plans"]},
        {"id": "m_da_bi", "course_id": "c_da", "order": 4, "title": "Power BI & Tableau",
         "duration_minutes": 300, "advanced_id": None,
         "content": "Data modeling, star schemas, DAX measures, and dashboard design. From query results to executive-grade reports.",
         "objectives": ["Design star schemas", "Write DAX measures that aggregate correctly", "Build dashboards that drive decisions"]},
        {"id": "m_da_story", "course_id": "c_da", "order": 5, "title": "Data Storytelling",
         "duration_minutes": 180, "advanced_id": None,
         "content": "Chart selection, narrative structure, audience adaptation, and the executive summary. Insight is wasted without communication.",
         "objectives": ["Match charts to questions", "Structure a data narrative", "Write executive summaries that get read"]},
        {"id": "m_da_ab", "course_id": "c_da", "order": 6, "title": "A/B Testing for Analysts",
         "duration_minutes": 240, "advanced_id": None,
         "content": "Test design, sample size, SRM detection, segment analysis, and the multiple-testing problem. Defensible experimentation.",
         "objectives": ["Power a test before launch", "Detect SRM and bucket leakage", "Interpret segmented results responsibly"]},
        {"id": "m_da_biz", "course_id": "c_da", "order": 7, "title": "Business Acumen for Analysts",
         "duration_minutes": 180, "advanced_id": None,
         "content": "Unit economics, financial statements, KPIs by function, and the language of executives.",
         "objectives": ["Read a P&L statement", "Pick KPIs aligned to function", "Speak to executives in their language"]},
    ]
    db.seed("modules", modules)

    quizzes = [
        # === Data Science ===
        {"module_id": "m_ds_py", "questions": [
            {"q": "What does the expression `[1, 2, 3] * 2` evaluate to in Python?",
             "options": ["[2, 4, 6]", "[1, 2, 3, 1, 2, 3]", "TypeError", "[[1, 2, 3], [1, 2, 3]]"], "answer": 1},
            {"q": "Why does `print(0.1 + 0.2 == 0.3)` print `False`?",
             "options": ["Python rounds floats by default", "IEEE 754 floating-point representation cannot exactly represent these values",
                         "`==` is not defined on floats", "Operator precedence evaluates the addition last"], "answer": 1},
            {"q": "A function uses `def f(x, items=[]): items.append(x); return items`. Calling `f(1)` then `f(2)` returns?",
             "options": ["[1] then [2]", "[1] then [1, 2]", "[2] then [1, 2]", "Raises an error on the second call"], "answer": 1},
            {"q": "Which of the following correctly produces a shallow copy of a list `xs`?",
             "options": ["`xs.copy()`", "`xs[:]`", "`list(xs)`", "All of the above"], "answer": 3},
            {"q": "What is the amortized time complexity of `list.append(x)` in CPython?",
             "options": ["O(n)", "O(log n)", "O(1) amortized", "O(n log n)"], "answer": 2},
        ]},
        {"module_id": "m_ds_pandas", "questions": [
            {"q": "What is the primary cause of a `SettingWithCopyWarning` in Pandas?",
             "options": ["Using `.copy()` unnecessarily", "Chained indexing on assignment, e.g. `df[df.a > 0]['b'] = 1`",
                         "Mixing `int` and `float` columns", "Setting `inplace=True`"], "answer": 1},
            {"q": "`df.merge(other, how='left', on='id')` returns rows where?",
             "options": ["Both `df` and `other` have a matching `id`", "All rows from `df` plus matched rows from `other`",
                         "All rows from `other` plus matched rows from `df`", "Rows with no match in either side"], "answer": 1},
            {"q": "Which selector is label-based and which is positional, in order?",
             "options": ["`.iloc` is label, `.loc` is positional", "`.loc` is label, `.iloc` is positional",
                         "Both are positional", "Both are label-based"], "answer": 1},
            {"q": "`pd.concat([a, b], axis=1)` does what when `a` and `b` have different indexes?",
             "options": ["Drops mismatched rows", "Aligns on index and fills mismatches with NaN",
                         "Raises ValueError", "Resets the index automatically"], "answer": 1},
            {"q": "Why is `df.apply(f, axis=1)` typically slower than a vectorized expression?",
             "options": ["It runs in a separate thread", "It iterates row-by-row in Python, defeating NumPy vectorization",
                         "It compresses data first", "It always converts to object dtype"], "answer": 1},
        ]},
        {"module_id": "m_ds_viz", "questions": [
            {"q": "Which chart type is most appropriate for comparing the rank of ~10 categories by a single metric?",
             "options": ["Pie chart", "Bar chart sorted by value", "3D column chart", "Donut chart"], "answer": 1},
            {"q": "Why are 3D charts generally discouraged in analytical communication?",
             "options": ["They render too slowly", "They distort perception of magnitude and obscure values",
                         "They aren't supported in matplotlib", "They violate the WCAG color contrast rules"], "answer": 1},
            {"q": "A 'pre-attentive' visual attribute is one that?",
             "options": ["Requires explanation in a legend", "Is processed before conscious attention, e.g. color, position, size",
                         "Only works in dark mode", "Increases the chart's file size"], "answer": 1},
            {"q": "When should you use a log scale on the y-axis?",
             "options": ["Always, it looks more scientific", "When the data spans multiple orders of magnitude",
                         "Only for time-series charts", "When values include negatives"], "answer": 1},
            {"q": "Best practice for color in charts intended for accessibility?",
             "options": ["Use red and green to indicate good/bad", "Encode meaning redundantly (color + shape/label) and pass contrast checks",
                         "Limit charts to grayscale only", "Use vibrant rainbows for engagement"], "answer": 1},
        ]},
        {"module_id": "m_ds_stats", "questions": [
            {"q": "A p-value of 0.03 in a two-sided test means?",
             "options": ["There is a 3% chance the null hypothesis is true",
                         "Assuming the null is true, the probability of observing data at least this extreme is 3%",
                         "The effect size is 3%", "The test has 97% statistical power"], "answer": 1},
            {"q": "The Central Limit Theorem states that?",
             "options": ["All real-world data is normally distributed",
                         "The sampling distribution of the sample mean approaches normality as n grows, regardless of the population distribution (with finite variance)",
                         "Increasing sample size always reduces bias", "Sample variance equals population variance for n > 30"], "answer": 1},
            {"q": "Statistical power is defined as?",
             "options": ["1 minus the significance level α", "The probability of rejecting H₀ when H₁ is true (1 − β)",
                         "The probability of a Type I error", "The width of the confidence interval"], "answer": 1},
            {"q": "Why is the Bonferroni correction sometimes too conservative?",
             "options": ["It assumes all tests are independent and equally important, inflating Type II error",
                         "It only works for one-sided tests", "It requires equal sample sizes",
                         "It cannot be used with continuous variables"], "answer": 0},
            {"q": "A 95% confidence interval for the mean means?",
             "options": ["There's a 95% probability the true mean lies in this interval",
                         "If we repeated the experiment many times, ~95% of constructed intervals would contain the true mean",
                         "The sample mean has a 95% probability of being correct", "The data is 95% reliable"], "answer": 1},
        ]},
        {"module_id": "m_ds_ml", "questions": [
            {"q": "What is the key behavioral difference between L1 and L2 regularization?",
             "options": ["L1 is faster to compute", "L1 induces sparsity (drives weights to exactly 0); L2 shrinks weights smoothly",
                         "L2 is for classification only", "L1 prevents underfitting; L2 prevents overfitting"], "answer": 1},
            {"q": "Bias–variance tradeoff in plain terms?",
             "options": ["Increasing model complexity always improves accuracy",
                         "Simple models tend to underfit (high bias); complex models tend to overfit (high variance) — the goal is to balance both",
                         "Variance and bias always sum to 1", "Bias is irrelevant for tree models"], "answer": 1},
            {"q": "Data leakage in ML training is most commonly caused by?",
             "options": ["Using too small a learning rate", "Including features that would not be available at prediction time, or fitting preprocessing on the full dataset before splitting",
                         "Training for too many epochs", "Using an unbalanced dataset"], "answer": 1},
            {"q": "Cross-validation primarily helps you?",
             "options": ["Increase your training set size", "Estimate generalization performance more reliably than a single train/test split",
                         "Speed up training", "Avoid tuning hyperparameters"], "answer": 1},
            {"q": "A model with 99% training accuracy and 60% test accuracy most likely exhibits?",
             "options": ["Underfitting", "Overfitting / high variance", "Class imbalance only", "Insufficient regularization on the test set"], "answer": 1},
        ]},
        {"module_id": "m_ds_eval", "questions": [
            {"q": "For a highly imbalanced binary classification task (1% positives), accuracy is a poor metric because?",
             "options": ["It cannot be computed when classes are imbalanced", "A model predicting 'negative' for everything scores 99%, providing no signal about positive recall",
                         "It penalizes false negatives too heavily", "It requires probability outputs"], "answer": 1},
            {"q": "ROC-AUC is preferred over PR-AUC when?",
             "options": ["The dataset is heavily imbalanced", "Class distribution is roughly balanced and both classes matter equally",
                         "You only care about precision", "You are doing regression"], "answer": 1},
            {"q": "Probability calibration matters most when?",
             "options": ["You only need the predicted class label", "Downstream decisions consume probabilities (e.g. expected-value optimization, thresholding by cost)",
                         "Your features are categorical", "Your dataset is small"], "answer": 1},
            {"q": "Stratified k-fold cross-validation is preferable to plain k-fold when?",
             "options": ["The dataset is time-series", "Classes are imbalanced and you want each fold to preserve class proportions",
                         "Features are highly correlated", "k is greater than 10"], "answer": 1},
            {"q": "Time-series cross-validation differs from random k-fold because?",
             "options": ["It uses more folds", "It preserves temporal order — training folds always precede validation folds — to avoid look-ahead bias",
                         "It requires PyTorch", "It uses stratification by default"], "answer": 1},
        ]},
        {"module_id": "m_ds_dl", "questions": [
            {"q": "Backpropagation computes gradients by?",
             "options": ["Random sampling of weights", "Applying the chain rule, propagating partial derivatives from the loss back through the network graph",
                         "Numerically perturbing each weight", "Linear regression on activations"], "answer": 1},
            {"q": "Why was ReLU widely adopted over sigmoid for hidden layers?",
             "options": ["ReLU outputs are bounded", "ReLU mitigates the vanishing-gradient problem and is computationally cheap",
                         "ReLU always produces sparse activations by design", "ReLU is differentiable everywhere"], "answer": 1},
            {"q": "Batch normalization primarily helps because?",
             "options": ["It reduces the size of the network", "It stabilizes layer-input distributions, allowing higher learning rates and faster convergence",
                         "It acts as a learned activation function", "It replaces dropout"], "answer": 1},
            {"q": "Transfer learning is most effective when?",
             "options": ["The source and target tasks are completely unrelated", "The target dataset is small and the source domain is related — reuse learned features and fine-tune the head",
                         "The source model is undertrained", "You have unlimited target data"], "answer": 1},
            {"q": "Adam optimizer combines which two ideas?",
             "options": ["Momentum and adaptive per-parameter learning rates (via running estimates of gradient moments)",
                         "Newton's method and gradient descent", "L1 and L2 regularization", "Dropout and batch normalization"], "answer": 0},
        ]},

        # === Generative AI ===
        {"module_id": "m_ai_llm", "questions": [
            {"q": "The 'attention' operation in a Transformer is mathematically?",
             "options": ["A convolution over tokens", "Softmax(QKᵀ / √d) · V — scaled dot-product attention",
                         "A recurrent state update", "A linear projection followed by tanh"], "answer": 1},
            {"q": "The KV cache during decoding stores?",
             "options": ["The user's previous prompts", "The keys and values for previously generated tokens, so they aren't recomputed each step",
                         "The full vocabulary embedding", "A backup of model weights"], "answer": 1},
            {"q": "A temperature of 0 in sampling means?",
             "options": ["Sampling fails", "Greedy decoding — always pick the argmax token (deterministic)",
                         "Uniform random sampling", "Sample only from top tokens above a fixed probability"], "answer": 1},
            {"q": "Top-p (nucleus) sampling samples from?",
             "options": ["The single most likely token", "The smallest set of tokens whose cumulative probability exceeds p",
                         "Exactly p tokens, where p is an integer", "Tokens with probability greater than p"], "answer": 1},
            {"q": "Why does context-window length quadratically affect compute (for vanilla attention)?",
             "options": ["The model parameters scale with length", "Self-attention computes pairwise interactions between every pair of tokens — O(n²) in sequence length",
                         "Tokenization is quadratic", "The vocabulary scales with context"], "answer": 1},
        ]},
        {"module_id": "m_ai_prompt", "questions": [
            {"q": "Chain-of-thought prompting most reliably improves performance on?",
             "options": ["Trivia recall", "Multi-step reasoning tasks where intermediate steps reduce error",
                         "Translation", "Spelling correction"], "answer": 1},
            {"q": "To reliably force JSON output, the strongest practice is?",
             "options": ["Asking 'please respond in JSON'", "Use the provider's structured-output / JSON-mode feature plus an explicit JSON schema and a parser fallback",
                         "Add 'JSON:' at the end of the prompt", "Lower the temperature to 0.1"], "answer": 1},
            {"q": "Few-shot examples should ideally be?",
             "options": ["Identical to the input you expect", "Diverse, representative of the input distribution, and ordered to demonstrate the task — not memorized templates",
                         "All positive cases", "As short as possible"], "answer": 1},
            {"q": "A key principle for defending against prompt injection?",
             "options": ["Use longer system prompts", "Treat retrieved/user content as untrusted, separate instructions from data, and limit privileged actions to trusted contexts",
                         "Lower the temperature", "Use only proprietary models"], "answer": 1},
            {"q": "Why is 'self-consistency' (sampling multiple chains and voting) effective?",
             "options": ["It's faster than a single sample", "Multiple independent reasoning paths reduce variance from any one chain's errors, especially on reasoning tasks",
                         "It removes hallucination entirely", "It compresses tokens"], "answer": 1},
        ]},
        {"module_id": "m_ai_embed", "questions": [
            {"q": "Cosine similarity is preferred over raw dot product when?",
             "options": ["Embeddings are L2-normalized — then they're equivalent; otherwise cosine removes magnitude effects",
                         "Vectors are sparse", "Dimensionality is below 100", "You need integer outputs"], "answer": 0},
            {"q": "Approximate Nearest Neighbor (ANN) indexes like HNSW trade off?",
             "options": ["Storage for accuracy", "Recall for query latency — they sacrifice exactness for sub-linear search",
                         "Throughput for batch size", "Embedding dimension for cosine accuracy"], "answer": 1},
            {"q": "Hybrid search typically combines?",
             "options": ["Two different embedding models", "Sparse keyword retrieval (e.g. BM25) with dense vector retrieval, fusing rankings",
                         "Two ANN indexes with different metrics", "Text and image embeddings"], "answer": 1},
            {"q": "Why might embedding similarity fail to capture relevance?",
             "options": ["Embeddings are unrelated to meaning", "Embeddings encode general semantic similarity, not task-specific relevance — same topic ≠ same answer",
                         "Cosine is not symmetric", "Embeddings can't be cached"], "answer": 1},
            {"q": "Re-ranking with a cross-encoder after initial retrieval improves quality because?",
             "options": ["Cross-encoders are faster than bi-encoders", "Cross-encoders attend jointly to query and candidate, capturing fine-grained relevance bi-encoders miss",
                         "They reduce embedding dimensionality", "They require less data"], "answer": 1},
        ]},
        {"module_id": "m_ai_rag", "questions": [
            {"q": "Smaller chunks in RAG generally improve retrieval precision but?",
             "options": ["Always reduce generation quality", "Risk losing surrounding context, fragmenting concepts that span multiple chunks",
                         "Make embeddings non-comparable", "Increase index size linearly"], "answer": 1},
            {"q": "Why does query rewriting often improve RAG?",
             "options": ["It shortens the user query", "User queries are often underspecified; rewriting (e.g. HyDE, expansion) aligns them to how the corpus is phrased",
                         "It removes the need for embeddings", "It bypasses the LLM"], "answer": 1},
            {"q": "Grounding in RAG means?",
             "options": ["Locking the model to a fixed temperature", "Instructing the model to answer strictly from retrieved context and to cite/abstain when context is insufficient",
                         "Pre-training on the corpus", "Disabling sampling"], "answer": 1},
            {"q": "A common failure mode of RAG when chunks contain mixed topics?",
             "options": ["Retrieval slows down", "Embeddings represent an average of topics, making them less discriminating — fix with topical chunking",
                         "The LLM crashes", "Vector dimension increases"], "answer": 1},
            {"q": "Which evaluation signal best distinguishes retrieval failures from generation failures?",
             "options": ["End-to-end accuracy alone", "Separate metrics: retrieval recall@k against gold passages, plus faithfulness/answer-correctness on the generation step",
                         "Latency", "Token count"], "answer": 1},
        ]},
        {"module_id": "m_ai_tools", "questions": [
            {"q": "Tool definitions for function calling are typically expressed as?",
             "options": ["Free-form descriptions", "JSON Schema with name, description, and typed parameters — used by the model to produce structured tool calls",
                         "Python pickles", "Markdown tables"], "answer": 1},
            {"q": "When the model returns a tool call, the correct loop is?",
             "options": ["Send the tool call back to the user", "Execute the tool, append its result as a tool message, and re-invoke the model — possibly multiple rounds",
                         "Reject the response and retry", "Use only the tool's first argument"], "answer": 1},
            {"q": "Parallel tool calls are useful when?",
             "options": ["Tools are mutually dependent", "Tools are independent and can be invoked simultaneously to reduce latency",
                         "Tools share state", "You only want one answer"], "answer": 1},
            {"q": "A robust tool-using agent should handle tool errors by?",
             "options": ["Crashing immediately", "Returning the error to the model with context so it can retry, fall back, or surface the failure",
                         "Ignoring the error silently", "Re-prompting the user every time"], "answer": 1},
            {"q": "Why prefer narrowly-scoped tools over a single 'do anything' tool?",
             "options": ["They cost more tokens", "Specific tools give the model clearer affordances and reduce miscalled actions",
                         "They are slower", "They require fewer tests"], "answer": 1},
        ]},
        {"module_id": "m_ai_agents", "questions": [
            {"q": "The ReAct pattern interleaves?",
             "options": ["Retrieval and ranking", "Reasoning (thoughts) and Acting (tool calls), letting the model plan and observe iteratively",
                         "Reading and Acting on user input only", "Reflection and Aggregation"], "answer": 1},
            {"q": "When should you prefer a deterministic workflow over an agent?",
             "options": ["When the task has a stable structure with known steps — predictable, cheaper, easier to evaluate",
                         "When you want maximum flexibility", "When latency is irrelevant", "When the LLM is small"], "answer": 0},
            {"q": "Long-running agents commonly fail by?",
             "options": ["Memory limits in Python", "Drifting off-task, looping, or compounding small errors over many steps",
                         "Cosine similarity collapsing", "Token cache invalidation"], "answer": 1},
            {"q": "A practical guardrail against runaway agents?",
             "options": ["Trust the model to stop on its own", "Hard caps on tool calls, time, and cost — plus explicit termination conditions",
                         "Increase temperature", "Run agents only on weekends"], "answer": 1},
            {"q": "Long-term memory in agents typically refers to?",
             "options": ["The context window", "Externalized persistent state (e.g. a database or vector store) the agent reads/writes across sessions",
                         "Cached embeddings only", "The model weights"], "answer": 1},
        ]},
        {"module_id": "m_ai_eval", "questions": [
            {"q": "A golden dataset for LLM evaluation is?",
             "options": ["The training data", "A curated set of inputs with known good outputs, used to track regressions and compare versions",
                         "Synthetic data only", "The most expensive examples"], "answer": 1},
            {"q": "LLM-as-judge can be unreliable because?",
             "options": ["It always agrees with humans", "Judges have biases (position, length, self-preference) — calibrate with human ratings and use pairwise comparison",
                         "It cannot read JSON", "It is too slow"], "answer": 1},
            {"q": "Why combine offline evals with online metrics?",
             "options": ["Offline evals are obsolete", "Offline catches regressions pre-release; online captures real user behavior and edge cases offline can't anticipate",
                         "Online metrics are free", "Offline evals require GPUs"], "answer": 1},
            {"q": "Faithfulness in RAG evaluation measures?",
             "options": ["Response latency", "Whether the answer is supported by the retrieved context, regardless of whether the answer is correct in general",
                         "User satisfaction", "Cost per query"], "answer": 1},
            {"q": "Effective input guardrails typically include?",
             "options": ["Only a system prompt", "PII scrubbing, jailbreak detection, topic classification, and policy enforcement — layered, not single-point",
                         "Banning all capital letters", "Setting temperature to 0"], "answer": 1},
        ]},

        # === Web Development ===
        {"module_id": "m_web_html", "questions": [
            {"q": "Why use `<button>` instead of `<div role='button'>` for an interactive button?",
             "options": ["`<button>` is shorter to type", "`<button>` is keyboard-focusable, announces correctly to assistive tech, and submits forms — all for free",
                         "`<div>` cannot have click handlers", "Browsers ignore `<div>` styling"], "answer": 1},
            {"q": "Correct ARIA usage rule?",
             "options": ["Add ARIA roles to every element for accessibility", "Prefer native semantic HTML; use ARIA only when semantics don't exist or need overriding",
                         "ARIA is a replacement for semantic HTML", "ARIA roles must be applied via JavaScript"], "answer": 1},
            {"q": "The `<picture>` element is primarily for?",
             "options": ["Animated GIFs", "Art direction and serving different image sources by viewport, format, or DPR",
                         "SVG fallbacks", "Replacing `<img>` entirely"], "answer": 1},
            {"q": "An HTML form submits via `GET` by default. To send sensitive credentials, you should use?",
             "options": ["GET with URL encoding", "POST over HTTPS — GET puts data in the URL where it's logged in history and referer headers",
                         "POST over HTTP", "Either, encoding doesn't matter"], "answer": 1},
            {"q": "Why does heading hierarchy matter beyond visual style?",
             "options": ["Search engines fine you for skipping levels", "It defines the document outline for assistive technology and SEO; skipped levels confuse navigation",
                         "Browsers refuse to render skipped levels", "Hierarchy only affects CSS"], "answer": 1},
        ]},
        {"module_id": "m_web_css", "questions": [
            {"q": "Specificity of `#main .item.active` vs `div.item.active.highlighted`?",
             "options": ["The second wins because it has more classes", "The first wins because IDs (specificity 1,0,0) outrank classes",
                         "They're equal", "Whichever is written later in CSS"], "answer": 1},
            {"q": "`position: sticky` requires?",
             "options": ["A fixed parent height only", "An inset value (top/left/etc.) and a scrollable ancestor that defines the sticky containing block",
                         "JavaScript polyfill in all browsers", "`overflow: hidden` on the parent"], "answer": 1},
            {"q": "Flexbox is best when?",
             "options": ["You need 2D layout (rows and columns simultaneously)", "You need 1D layout — distributing items along a single axis with flexible sizing",
                         "Building a CSS grid system", "Working with print stylesheets"], "answer": 1},
            {"q": "`rem` vs `em` units?",
             "options": ["They are identical", "`em` is relative to the parent's font-size; `rem` is relative to the root (`html`) font-size",
                         "Both are absolute pixel values", "`em` is for spacing, `rem` is for fonts only"], "answer": 1},
            {"q": "CSS containment (`contain: content`) primarily helps with?",
             "options": ["Color management", "Performance — isolating a subtree so layout/paint changes don't affect siblings",
                         "Accessibility", "Animation smoothness on the GPU"], "answer": 1},
        ]},
        {"module_id": "m_web_js", "questions": [
            {"q": "`var` vs `let` declarations differ in?",
             "options": ["Only syntax", "Scope (function vs block) and hoisting behavior (`let` has a temporal dead zone)",
                         "Type enforcement", "Performance"], "answer": 1},
            {"q": "What does `Promise.all` do if one promise rejects?",
             "options": ["Waits for all to settle, then reports failures", "Rejects immediately with the first error; use `Promise.allSettled` if you need every outcome",
                         "Retries the failed promise", "Resolves with undefined"], "answer": 1},
            {"q": "Why does this print `undefined`? `const o = {x: 1, get: () => this.x}; console.log(o.get());`",
             "options": ["Arrow functions don't bind their own `this` — `this` is the enclosing scope (often the module/window), where `x` is undefined",
                         "Getters aren't supported on object literals", "`this.x` is always undefined in strict mode", "`get` is a reserved word"], "answer": 0},
            {"q": "The event loop processes microtasks (e.g. Promise callbacks) relative to macrotasks (e.g. setTimeout)?",
             "options": ["Macrotasks run first", "All microtasks drain after each macrotask, before rendering or the next macrotask",
                         "They alternate one-for-one", "Microtasks only run on user input"], "answer": 1},
            {"q": "A closure is created when?",
             "options": ["You use the `function` keyword", "An inner function references variables from its enclosing scope, keeping those bindings alive after the outer function returns",
                         "You declare a class", "You import a module"], "answer": 1},
        ]},
        {"module_id": "m_web_dom", "questions": [
            {"q": "Event delegation is the practice of?",
             "options": ["Removing all event listeners", "Attaching a single listener to a common ancestor and using `event.target` to identify the source — efficient for many similar children",
                         "Using `addEventListener('delegate', ...)`", "Disabling default behavior"], "answer": 1},
            {"q": "`event.target` vs `event.currentTarget`?",
             "options": ["They're the same", "`target` is the element that triggered the event; `currentTarget` is the element the listener was attached to",
                         "`currentTarget` is always the document", "`target` always equals `this`"], "answer": 1},
            {"q": "Difference between `innerHTML` and `textContent` for inserting user input?",
             "options": ["None", "`innerHTML` parses HTML and is XSS-prone; `textContent` inserts as text and is safe by default",
                         "`textContent` is deprecated", "`innerHTML` is faster and always preferred"], "answer": 1},
            {"q": "Debouncing vs throttling, in one line?",
             "options": ["They're synonyms", "Debounce waits for inactivity to fire once; throttle fires at most once per interval during continuous activity",
                         "Throttle waits forever; debounce is instant", "Both block the main thread"], "answer": 1},
            {"q": "IntersectionObserver is preferred over scroll-event handlers because?",
             "options": ["It works on older browsers", "It's async, batched off the main thread, and doesn't fire on every scroll pixel",
                         "It has a smaller API surface", "It supports CSS transitions"], "answer": 1},
        ]},
        {"module_id": "m_web_flask", "questions": [
            {"q": "Flask blueprints exist to?",
             "options": ["Generate CSS scaffolding", "Split a large app into modular components with their own routes, templates, and static files",
                         "Replace WSGI", "Manage virtual environments"], "answer": 1},
            {"q": "The `g` object in Flask is scoped to?",
             "options": ["The application's lifetime", "A single request — it's reset between requests and useful for per-request state like DB connections",
                         "The current user session", "All requests from one IP"], "answer": 1},
            {"q": "Why is rendering `{{ user_input }}` in a Jinja template safe by default?",
             "options": ["Jinja autoescapes HTML in templates ending in `.html`, preventing reflected XSS unless you explicitly mark `|safe`",
                         "Browsers strip scripts automatically", "Jinja runs in a sandbox VM", "Flask sanitizes all responses"], "answer": 0},
            {"q": "CSRF protection in form-based Flask apps works by?",
             "options": ["Validating IP addresses", "Issuing an unpredictable token on form render and verifying it on submission so cross-site forms can't forge requests",
                         "Requiring HTTPS only", "Encrypting cookies with HMAC"], "answer": 1},
            {"q": "An N+1 query problem in a Flask + SQLAlchemy app looks like?",
             "options": ["A single query running 100 times slower", "Loading N parent rows then issuing one additional query per parent to fetch its children — fix with eager loading",
                         "A schema with 100 tables", "Running migrations N times"], "answer": 1},
        ]},
        {"module_id": "m_web_rest", "questions": [
            {"q": "PUT vs PATCH semantically?",
             "options": ["They are identical", "PUT replaces the resource representation entirely; PATCH applies a partial update",
                         "PUT is idempotent only for collections", "PATCH is for nested resources"], "answer": 1},
            {"q": "401 Unauthorized vs 403 Forbidden?",
             "options": ["Both mean the same thing", "401 means the request lacks valid authentication; 403 means the user is authenticated but not allowed",
                         "403 means the resource doesn't exist", "401 is only for OAuth"], "answer": 1},
            {"q": "Idempotency in HTTP means?",
             "options": ["The endpoint runs fast", "Repeating the same request has the same effect as making it once — important for safe retries",
                         "The response is cacheable", "The endpoint has no body"], "answer": 1},
            {"q": "A pragmatic API versioning strategy?",
             "options": ["Break the contract whenever needed", "Version explicitly (URL or header) and avoid breaking changes within a version; add fields rather than rename",
                         "Skip versioning — clients should always update", "Use random UUIDs as version numbers"], "answer": 1},
            {"q": "Why design a consistent error envelope (e.g. `{error: {code, message, details}}`)?",
             "options": ["It's required by REST", "Clients can handle errors generically without parsing free-form strings; aids logging and DX",
                         "It reduces response size", "It's faster to serialize"], "answer": 1},
        ]},
        {"module_id": "m_web_auth", "questions": [
            {"q": "Storing JWTs in `localStorage` exposes them to?",
             "options": ["CSRF only", "XSS — any injected script can read localStorage; HttpOnly cookies are immune to JS access",
                         "Server-side replay", "Browser memory limits"], "answer": 1},
            {"q": "`SameSite=Strict` on a cookie means?",
             "options": ["It's only sent to the same domain", "It's never sent on cross-site requests, including top-level navigations — strongest CSRF defense, can break some flows",
                         "It encrypts the cookie", "It expires after one request"], "answer": 1},
            {"q": "Why use bcrypt/argon2 for passwords instead of SHA-256?",
             "options": ["They produce shorter hashes", "They are intentionally slow and salted, making offline brute-force attacks infeasible at scale",
                         "They are quantum-resistant", "They allow encryption (reversible)"], "answer": 1},
            {"q": "OAuth 2.0 Authorization Code with PKCE is the recommended flow for?",
             "options": ["Server-to-server clients with stored secrets", "Public clients (SPAs, mobile) that cannot safely hold a client secret",
                         "Resource servers", "Backend cron jobs"], "answer": 1},
            {"q": "To prevent session fixation, on successful login you should?",
             "options": ["Set a longer expiry", "Regenerate the session identifier so a pre-authenticated session token can't be reused",
                         "Log the user out immediately after login", "Use a longer password"], "answer": 1},
        ]},

        # === Digital Marketing ===
        {"module_id": "m_dm_intro", "questions": [
            {"q": "A healthy LTV:CAC ratio is generally considered?",
             "options": ["1:1", "Around 3:1 — enough margin to fund growth while signaling acquisition isn't unprofitable",
                         "10:1 — anything less is failure", "Doesn't matter; only revenue matters"], "answer": 1},
            {"q": "Top-of-funnel marketing primarily aims to?",
             "options": ["Close deals", "Generate awareness and reach prospects who don't yet know they have the problem",
                         "Upsell existing customers", "Reduce churn"], "answer": 1},
            {"q": "Brand vs performance marketing?",
             "options": ["They're identical", "Brand builds long-term mental availability and pricing power; performance drives short-term measurable response — both are needed",
                         "Brand has higher ROAS", "Performance is for B2B only"], "answer": 1},
            {"q": "Why is CAC payback period a critical metric?",
             "options": ["It's just for accounting", "It measures how long until acquired revenue repays acquisition cost — drives cash-flow planning and growth pacing",
                         "It's the same as LTV", "It only matters at IPO"], "answer": 1},
            {"q": "A common AIDA framework misuse?",
             "options": ["Treating it as a fixed linear sequence in a non-linear world of touchpoints",
                         "Skipping the 'Awareness' stage", "Using it for B2B", "Combining it with the marketing funnel"], "answer": 0},
        ]},
        {"module_id": "m_dm_seo", "questions": [
            {"q": "Core Web Vitals (2026) measure?",
             "options": ["Server uptime", "LCP (largest contentful paint), INP (interaction-to-next-paint), CLS (layout shift) — UX-centric speed signals",
                         "Number of backlinks", "Domain age"], "answer": 1},
            {"q": "A canonical tag (`<link rel='canonical'>`) tells search engines?",
             "options": ["The page is the homepage", "Which URL is the preferred version when near-duplicate pages exist, consolidating ranking signals",
                         "The page should not be crawled", "The page is mobile-only"], "answer": 1},
            {"q": "`robots.txt` reliably prevents?",
             "options": ["Indexing of pages", "Crawling of pages by compliant bots — but not indexing (use `noindex` for that, since pages can still be indexed via external links)",
                         "Sitemaps", "PageRank flow"], "answer": 1},
            {"q": "Backlink quality is more important than quantity primarily because?",
             "options": ["Search engines count links manually", "Modern algorithms weight authority, topical relevance, and trust — low-quality links can be ignored or penalized",
                         "Quantity doesn't affect rank at all", "Quality links are easier to get"], "answer": 1},
            {"q": "EEAT in Google's quality framework stands for?",
             "options": ["Experience, Expertise, Authoritativeness, Trustworthiness — signals used to assess content quality, especially in YMYL topics",
                         "Engagement, Efficiency, Authority, Time", "External, Earned, Approved, Tracked", "Email, Engagement, Ad, Tracking"], "answer": 0},
        ]},
        {"module_id": "m_dm_content", "questions": [
            {"q": "The 'pillar–cluster' content model is designed to?",
             "options": ["Save server space", "Build topical authority by linking a broad pillar to deep cluster pages, signaling expertise and improving internal navigation",
                         "Bypass duplicate-content rules", "Replace SEO entirely"], "answer": 1},
            {"q": "Skyscraper technique works by?",
             "options": ["Building tall web pages", "Finding the best-performing content on a topic, creating a substantially better version, then earning links via outreach",
                         "Buying ads on competitor sites", "Publishing daily content"], "answer": 1},
            {"q": "Why is content distribution often more leveraged than content creation?",
             "options": ["Creation is automated", "Most content underperforms not for lack of quality but lack of reach — distribution multiplies a fixed asset's return",
                         "Distribution is free", "Algorithms ignore quality"], "answer": 1},
            {"q": "A content audit's primary goal is to?",
             "options": ["Delete everything older than a year", "Identify what to keep, update, consolidate, or prune based on performance and relevance — quality over volume",
                         "Increase total page count", "Rank for new keywords"], "answer": 1},
            {"q": "Repurposing a long-form article into short-form social posts is effective because?",
             "options": ["Audiences consume the same content the same way on every platform",
                         "Audiences differ by platform and attention budget; native formats lift reach and recall",
                         "It avoids SEO duplicate penalties", "Long-form is obsolete"], "answer": 1},
        ]},
        {"module_id": "m_dm_paid", "questions": [
            {"q": "ROAS is calculated as?",
             "options": ["Profit ÷ Cost", "Revenue ÷ Ad Spend (not the same as profitability — high ROAS can still be unprofitable on a margin basis)",
                         "Conversions ÷ Clicks", "Impressions ÷ Spend"], "answer": 1},
            {"q": "Quality Score in Google Ads is determined primarily by?",
             "options": ["Total spend", "Expected CTR, ad relevance, and landing-page experience — affects both rank and CPC",
                         "Bid amount only", "Account age"], "answer": 1},
            {"q": "Target ROAS (tROAS) is a smart-bidding strategy that?",
             "options": ["Fixes CPC manually", "Sets bids automatically to maximize conversion value within a target ROAS — needs conversion-value data and volume",
                         "Caps daily spend", "Disables learning"], "answer": 1},
            {"q": "Why do iOS 14+ changes complicate Meta Ads attribution?",
             "options": ["They block all Meta ads", "App Tracking Transparency reduces signal — many users opt out, leading to modeled rather than deterministic attribution",
                         "They require GDPR consent in the US", "They mandate manual UTMs"], "answer": 1},
            {"q": "Frequency capping addresses?",
             "options": ["Daily budget overruns", "Ad fatigue — showing the same person an ad too often hurts CTR, brand sentiment, and ROI",
                         "Cookie syncing", "Brand safety"], "answer": 1},
        ]},
        {"module_id": "m_dm_social", "questions": [
            {"q": "Most modern feed algorithms primarily optimize for?",
             "options": ["Chronological order", "Predicted engagement and time spent — content that drives interactions and watch-time gets distribution",
                         "Number of followers", "Hashtag count"], "answer": 1},
            {"q": "The single biggest lever for short-form video retention is?",
             "options": ["Video length", "The opening hook — the first ~3 seconds determine whether the algorithm continues distribution",
                         "Filters", "Posting frequency"], "answer": 1},
            {"q": "Organic reach has declined across platforms primarily because?",
             "options": ["Algorithms suppress organic content arbitrarily", "Supply of content has grown far faster than user attention; platforms ration distribution to maintain UX and monetization",
                         "Users stopped following accounts", "Hashtags broke"], "answer": 1},
            {"q": "A defensible way to measure influencer marketing ROI?",
             "options": ["Total impressions", "Unique tracking links / promo codes plus brand-lift studies — to attribute incremental revenue, not just views",
                         "Number of followers", "Likes per post"], "answer": 1},
            {"q": "Community-building vs broadcasting differs in?",
             "options": ["Volume of posts", "Direction of interaction — communities create two-way value via moderation, conversation, and member contribution; broadcasting is one-way",
                         "Channel choice only", "Use of paid promotion"], "answer": 1},
        ]},
        {"module_id": "m_dm_email", "questions": [
            {"q": "Why are email open rates now an unreliable performance signal?",
             "options": ["Apple's Mail Privacy Protection pre-loads tracking pixels, inflating apparent opens regardless of real opens",
                         "Gmail blocks all pixels", "Inboxes deduplicate emails", "Open rate was never measurable"], "answer": 0},
            {"q": "Hard bounce vs soft bounce?",
             "options": ["They're the same", "Hard = permanent (invalid address, blocked); soft = temporary (full inbox, transient server issue) — handle them differently",
                         "Hard means spam", "Soft is irrelevant"], "answer": 1},
            {"q": "Deliverability is influenced most by?",
             "options": ["Subject line length", "Sender reputation (engagement signals, complaint rate, authentication: SPF/DKIM/DMARC) — not just content",
                         "Email volume per send", "Number of links"], "answer": 1},
            {"q": "List segmentation typically improves results because?",
             "options": ["Smaller lists send faster", "Relevance lifts engagement and reduces unsubscribes; algorithms reward engaged senders with better placement",
                         "It bypasses spam filters", "It avoids GDPR"], "answer": 1},
            {"q": "A best practice for re-engagement campaigns?",
             "options": ["Email more often", "Identify dormant subscribers and send a focused win-back sequence; if no response, suppress to protect deliverability",
                         "Buy a new list", "Switch to plain text"], "answer": 1},
        ]},
        {"module_id": "m_dm_analytics", "questions": [
            {"q": "Last-click attribution systematically?",
             "options": ["Over-credits brand awareness", "Over-credits bottom-funnel touchpoints (e.g. branded search, retargeting) and under-credits upper-funnel discovery",
                         "Is the most accurate model", "Ignores paid media"], "answer": 1},
            {"q": "UTM parameters allow tracking of?",
             "options": ["User IP addresses", "Campaign source, medium, name, content, and term — appended to URLs and read by analytics tools for attribution",
                         "Device type only", "Page load times"], "answer": 1},
            {"q": "GA4 differs fundamentally from Universal Analytics in?",
             "options": ["Just UI", "Event-based data model instead of session-based, with cross-platform users and built-in modeling for unattributed conversions",
                         "Pricing", "Only available for mobile"], "answer": 1},
            {"q": "Incrementality testing measures?",
             "options": ["Whether a campaign increased ROAS", "The causal lift attributable to marketing by comparing exposed vs control (holdout) audiences — beyond correlational attribution",
                         "Whether the campaign was creative", "Total impressions delivered"], "answer": 1},
            {"q": "A cohort retention chart shows?",
             "options": ["Total active users", "How successive cohorts (e.g. signup-month cohorts) retain over time — surfaces product-led growth or churn dynamics",
                         "Just MAU", "Channel performance"], "answer": 1},
        ]},

        # === Product Management ===
        {"module_id": "m_pm_think", "questions": [
            {"q": "The Jobs-to-be-Done (JTBD) framework reframes products as?",
             "options": ["Feature sets", "Solutions people 'hire' to make progress on a job — focusing on the underlying motivation, context, and outcome, not demographics",
                         "Engineering specs", "Marketing campaigns"], "answer": 1},
            {"q": "'Outcome over output' means?",
             "options": ["Ship more features", "Measure success by user/business outcomes (behavior change, value delivered), not feature counts or velocity",
                         "Outcomes are vanity metrics", "Output is irrelevant"], "answer": 1},
            {"q": "A defensible opportunity sizing requires at minimum?",
             "options": ["A revenue target", "Market sizing (TAM/SAM/SOM), frequency of the job, willingness to pay, and reachability — each with stated assumptions",
                         "VC interest", "Executive approval"], "answer": 1},
            {"q": "MVP (Minimum Viable Product) is best understood as?",
             "options": ["A buggy first version", "The smallest experiment that validates or invalidates a critical assumption with real users — learning, not launching",
                         "The roadmap's first quarter", "A free tier"], "answer": 1},
            {"q": "Product-market fit indicators usually include?",
             "options": ["High social media followers", "Strong retention, organic growth, customers pulling for more, and clear 'very disappointed if removed' signal",
                         "TechCrunch coverage", "VC valuation"], "answer": 1},
        ]},
        {"module_id": "m_pm_research", "questions": [
            {"q": "A 'leading' interview question to avoid?",
             "options": ["Tell me about the last time you tried to solve this problem", "Would you use a feature that lets you do X faster? — pre-supposes desire and a solution",
                         "What did you do next?", "Why was that frustrating?"], "answer": 1},
            {"q": "Why are 5 users often enough for usability testing?",
             "options": ["It's a regulatory minimum", "Diminishing returns: ~5 users surface ~85% of usability issues; further users mostly repeat findings",
                         "Time constraints", "Statistical significance"], "answer": 1},
            {"q": "Quant vs qual research roles?",
             "options": ["Qual is for early-stage; quant for later — they don't mix", "Qual generates hypotheses and explains 'why'; quant tests and sizes them — they're complementary",
                         "Quant is more rigorous and qual is optional", "Qual is for designers; quant for analysts"], "answer": 1},
            {"q": "Survey design pitfall to avoid?",
             "options": ["Asking too few questions", "Double-barrelled questions (asking two things in one) — answers become uninterpretable",
                         "Including a free-text field", "Randomizing question order"], "answer": 1},
            {"q": "Synthesizing qualitative research is best done by?",
             "options": ["Picking the most quotable user", "Coding observations into themes, looking for recurring patterns and disconfirming evidence — structured, not vibes-based",
                         "Counting words", "Trusting the loudest user"], "answer": 1},
        ]},
        {"module_id": "m_pm_road", "questions": [
            {"q": "RICE prioritization stands for?",
             "options": ["Reach, Impact, Confidence, Effort — divides scored impact by effort, weighted by confidence in your estimates",
                         "Risk, Insight, Cost, Effort", "Revenue, Investment, Cycle, ETA", "Research, Iteration, Cost, Execution"], "answer": 0},
            {"q": "Now-Next-Later roadmaps work better than dated quarterly roadmaps because?",
             "options": ["They are cheaper to produce", "They communicate sequence and priority without false-precision commitments, accommodating real-world uncertainty",
                         "They are easier to defend in board meetings", "They lock teams into Gantt-style plans"], "answer": 1},
            {"q": "MoSCoW (Must/Should/Could/Won't) is most useful for?",
             "options": ["Yearly strategic planning", "Scoping a single release — making explicit what's in vs out, especially the 'Won't this round'",
                         "Setting OKRs", "Hiring decisions"], "answer": 1},
            {"q": "Why is 'Confidence' a multiplier in RICE?",
             "options": ["It's a buffer for engineering", "It penalizes scores built on weak assumptions, forcing teams to discount speculative reach/impact estimates",
                         "It's optional", "It rewards higher reach"], "answer": 1},
            {"q": "Stakeholder alignment is most fragile when?",
             "options": ["Stakeholders disagree publicly", "There's apparent agreement on goals but hidden disagreement on metrics, scope, or trade-offs — surface those explicitly",
                         "Roadmaps are visible", "Engineers are involved"], "answer": 1},
        ]},
        {"module_id": "m_pm_prd", "questions": [
            {"q": "A well-formed user story follows the pattern?",
             "options": ["The product should do X", "As a [persona], I want [capability], so that [benefit] — anchored in user value, not features",
                         "When clicked, X happens", "Engineering will build X"], "answer": 1},
            {"q": "Given–When–Then acceptance criteria are useful because?",
             "options": ["They use natural language only", "They describe behavior in testable terms (precondition, trigger, expected outcome) — usable by QA and as automated tests",
                         "They're shorter than user stories", "They eliminate edge cases"], "answer": 1},
            {"q": "Non-functional requirements typically include?",
             "options": ["Button colors and copy", "Performance, scalability, security, accessibility, reliability — qualities of how the system behaves, not what it does",
                         "Bug fixes", "Sprint cadence"], "answer": 1},
            {"q": "INVEST criteria for user stories — the 'I' stands for?",
             "options": ["Iterative", "Independent — stories should be deliverable in any order without strong coupling",
                         "Intentional", "Important"], "answer": 1},
            {"q": "Edge cases should appear in a PRD where?",
             "options": ["Nowhere; engineers will figure it out", "Explicitly in acceptance criteria and a dedicated edge-case section — what should happen on empty/error/limit states",
                         "Only in QA test plans", "In the appendix"], "answer": 1},
        ]},
        {"module_id": "m_pm_metrics", "questions": [
            {"q": "AARRR (Pirate Metrics) stages?",
             "options": ["Acquisition, Activation, Retention, Referral, Revenue — a framework to diagnose where the funnel breaks",
                         "Activation, Activity, Reach, Revenue, ROI", "Awareness, Adoption, Reach, Reactivation, Renewal", "All Active Recurring Revenue Records"], "answer": 0},
            {"q": "A North Star Metric should be?",
             "options": ["Revenue, always", "A single metric that captures the core value delivered to users and predicts long-term business outcomes — actionable, measurable, leading",
                         "Whatever the CEO chooses", "Total signups"], "answer": 1},
            {"q": "DAU/MAU ratio measures?",
             "options": ["Growth rate", "Stickiness — what fraction of monthly users come back daily; higher = habit-forming product",
                         "Churn rate", "ARPU"], "answer": 1},
            {"q": "An example of a vanity metric?",
             "options": ["Active users", "Total cumulative signups — grows monotonically and can't decline, regardless of product health",
                         "Retention curve", "Activation rate"], "answer": 1},
            {"q": "Leading vs lagging indicators?",
             "options": ["Leading is more important", "Leading indicators predict future outcomes (e.g. activation rate); lagging measure past results (e.g. revenue) — both matter",
                         "Lagging indicators are useless", "They are synonymous"], "answer": 1},
        ]},
        {"module_id": "m_pm_exp", "questions": [
            {"q": "Minimum Detectable Effect (MDE) is?",
             "options": ["The smallest improvement worth shipping", "The smallest true effect your test can reliably detect given sample size, variance, and chosen significance/power",
                         "Always 5%", "The mean of the metric"], "answer": 1},
            {"q": "'Peeking' at A/B test results before the planned end inflates?",
             "options": ["Sample size", "False-positive rate — repeated significance tests on accumulating data raise Type I error above the nominal α",
                         "Effect size", "Power"], "answer": 1},
            {"q": "Sample Ratio Mismatch (SRM) is?",
             "options": ["Different conversion rates per variant", "Observed traffic split materially differs from the configured split — indicates broken assignment, invalidating results",
                         "Difference in audience demographics", "Normal variance"], "answer": 1},
            {"q": "Multiple-testing correction (e.g. Bonferroni or BH) is needed when?",
             "options": ["You run one test at α = 0.05", "You evaluate many metrics or segments in one experiment — uncorrected α inflates false positives",
                         "Sample size is large", "Variant count is exactly two"], "answer": 1},
            {"q": "Novelty effects bias results when?",
             "options": ["Tests are too long", "Users react to change itself rather than the underlying feature — short tests overstate impact; longer or staged tests mitigate",
                         "The variant is identical to control", "Sample size is huge"], "answer": 1},
        ]},
        {"module_id": "m_pm_launch", "questions": [
            {"q": "A 'soft launch' is primarily about?",
             "options": ["Quiet PR", "Validating product readiness with a limited audience to find bugs, measure activation, and refine before a broader launch",
                         "Reducing legal exposure", "Avoiding press attention forever"], "answer": 1},
            {"q": "A positioning statement template usually contains?",
             "options": ["A pricing tier", "Target customer, category, key benefit, and primary differentiation from alternatives — focus, not features",
                         "Slogan and logo", "Roadmap dates"], "answer": 1},
            {"q": "Feature flags primarily enable?",
             "options": ["A/B testing only", "Decoupling deploy from release — staged rollout, kill-switch, segment targeting, and reversible launches",
                         "Branch-based development", "Slack notifications"], "answer": 1},
            {"q": "When choosing a launch tier (silent / private beta / public / tier-1 launch), the dominant factor is?",
             "options": ["Engineering preference", "Risk and uncertainty — riskier launches start narrow, gather evidence, then expand",
                         "Marketing budget", "Press contacts"], "answer": 1},
            {"q": "'Crossing the chasm' refers to the difficulty of?",
             "options": ["Migrating data", "Moving from early adopters to the early-majority pragmatist segment, which has different needs and buying criteria",
                         "Internationalization", "Launching on mobile"], "answer": 1},
        ]},

        # === Data Analytics ===
        {"module_id": "m_da_excel", "questions": [
            {"q": "INDEX-MATCH is often preferred over VLOOKUP because?",
             "options": ["It's shorter syntax", "It can look up to the left of the search column and is more robust to column insertions",
                         "It's required by Microsoft", "It works without arguments"], "answer": 1},
            {"q": "An absolute cell reference in Excel uses?",
             "options": ["`!A1`", "`$A$1` — locks both column and row when copied", "`A1$$`", "`@A1`"], "answer": 1},
            {"q": "PivotTables are best for?",
             "options": ["Storing raw transactional data", "Ad-hoc aggregation, grouping, and cross-tabulation without writing formulas",
                         "Charting time series", "Running ML models"], "answer": 1},
            {"q": "Power Query is primarily used for?",
             "options": ["Building dashboards", "ETL — connecting, cleaning, reshaping, and combining data sources into a refreshable table",
                         "Sending emails", "Running A/B tests"], "answer": 1},
            {"q": "A common SUMIFS gotcha?",
             "options": ["It doesn't support multiple criteria", "Criteria ranges must be the same shape as the sum range; mismatched shapes return #VALUE",
                         "It only works on numbers", "It cannot use cell references"], "answer": 1},
        ]},
        {"module_id": "m_da_sql1", "questions": [
            {"q": "INNER JOIN vs LEFT JOIN differs in?",
             "options": ["Performance only", "INNER returns only matched rows; LEFT returns all rows from the left table with NULLs for unmatched right-side columns",
                         "Index usage", "Whether NULLs are allowed"], "answer": 1},
            {"q": "Why does `WHERE column = NULL` return no rows even when NULLs exist?",
             "options": ["NULL is not a value but 'unknown' in SQL three-valued logic — use `IS NULL` instead",
                         "It's a syntax error", "NULL is automatically excluded from WHERE", "NULL is treated as 0"], "answer": 0},
            {"q": "WHERE vs HAVING?",
             "options": ["They're aliases", "WHERE filters rows before aggregation; HAVING filters after aggregation (used with GROUP BY)",
                         "HAVING is faster", "WHERE doesn't work with GROUP BY"], "answer": 1},
            {"q": "`SELECT DISTINCT a, b FROM t` returns?",
             "options": ["Distinct values of `a`, ignoring `b`", "Distinct combinations of `(a, b)` — DISTINCT applies to the entire row, not the first column",
                         "An error if there are duplicates", "All rows in random order"], "answer": 1},
            {"q": "Logical SQL execution order (simplified)?",
             "options": ["SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY", "FROM/JOIN → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT — written and executed orders differ",
                         "ORDER BY → SELECT → FROM", "It's the same as written order"], "answer": 1},
        ]},
        {"module_id": "m_da_sql2", "questions": [
            {"q": "Window functions differ from GROUP BY because?",
             "options": ["They are faster", "They compute over a window of rows without collapsing them — each input row keeps its identity in the output",
                         "They require DISTINCT", "They only return one row"], "answer": 1},
            {"q": "Difference between ROW_NUMBER, RANK, and DENSE_RANK on ties?",
             "options": ["They are identical", "ROW_NUMBER assigns unique sequential numbers; RANK leaves gaps after ties; DENSE_RANK does not leave gaps",
                         "RANK is for floats only", "DENSE_RANK is deprecated"], "answer": 1},
            {"q": "CTE (`WITH ...`) vs subquery — primary advantage of CTEs?",
             "options": ["Always faster", "Readability and reuse within the query, plus support for recursive queries",
                         "Required for joins", "Bypass query planner"], "answer": 1},
            {"q": "LAG(col) OVER (PARTITION BY x ORDER BY y) returns?",
             "options": ["The maximum value of `col` within partition", "The value of `col` from the previous row within each partition, ordered by y — useful for time-series differences",
                         "A random value", "The first value of the partition"], "answer": 1},
            {"q": "EXPLAIN (or EXPLAIN ANALYZE) is used to?",
             "options": ["Format SQL prettily", "Inspect the planner's chosen execution strategy — joins, indexes, scan types — to diagnose performance",
                         "Comment on queries", "Rewrite queries automatically"], "answer": 1},
        ]},
        {"module_id": "m_da_bi", "questions": [
            {"q": "A star schema is preferred over a snowflake schema when?",
             "options": ["Storage is the main constraint", "Read performance and dashboard simplicity matter more than normalization — fewer joins, broader dimensions",
                         "You have only fact tables", "You don't have a BI tool"], "answer": 1},
            {"q": "In Power BI, a DAX measure is?",
             "options": ["A static column", "An aggregation expression evaluated at query time in the filter context — recalculated per visual",
                         "A row-level transformation", "A relationship definition"], "answer": 1},
            {"q": "Cardinality in BI data modeling matters because?",
             "options": ["It affects only file size", "It determines join correctness — one-to-many is the common safe case; many-to-many often signals modeling problems",
                         "It controls colors", "It affects DAX syntax"], "answer": 1},
            {"q": "Slowly Changing Dimension Type 2 captures?",
             "options": ["Only the latest value", "Historical changes by inserting a new row per change, with effective-from and -to dates — preserves history",
                         "Time of last refresh", "Schema migrations"], "answer": 1},
            {"q": "ELT vs ETL differs in?",
             "options": ["Just naming", "Order — ELT loads raw data into the warehouse first and transforms in-database (leveraging warehouse compute)",
                         "ELT is for streaming only", "ETL is deprecated"], "answer": 1},
        ]},
        {"module_id": "m_da_story", "questions": [
            {"q": "For an executive audience, a dashboard should emphasize?",
             "options": ["Every available chart", "A small number of headline metrics, trends, exceptions, and the so-what — supporting decisions, not data dumps",
                         "Granular row-level details", "Maximum color variety"], "answer": 1},
            {"q": "Best chart type for showing the contribution of parts to a whole with ~3 categories?",
             "options": ["Bar chart with totals", "Stacked bar or a clearly labeled donut/pie — but bars are usually safer above a few categories",
                         "Scatter plot", "Histogram"], "answer": 1},
            {"q": "The 'lede' in a data story is?",
             "options": ["A footnote", "The single most important takeaway, placed up front so a busy reader gets value even if they stop reading",
                         "A methodology section", "The data source"], "answer": 1},
            {"q": "A common color misuse in dashboards?",
             "options": ["Using only blue", "Encoding red/green for good/bad without redundant labels — fails for color-blind users and looks alarmist",
                         "Using grayscale only", "Matching brand colors"], "answer": 1},
            {"q": "Effective storytelling structure for an analysis?",
             "options": ["Methodology, then data, then conclusion at the end", "Lead with the answer, then evidence, then methodology and caveats — match cognitive load to audience",
                         "Chronological order of analysis", "Tables only, no narrative"], "answer": 1},
        ]},
        {"module_id": "m_da_ab", "questions": [
            {"q": "Before launching a test, the most important step is?",
             "options": ["Pick a creative variant", "Power calculation — given baseline rate, MDE, and α, determine required sample size and test duration",
                         "Set up dashboards", "Notify the press"], "answer": 1},
            {"q": "Detecting Sample Ratio Mismatch matters because?",
             "options": ["It tells you the variant is better", "Differing traffic split from configuration signals broken randomization — the experiment is invalid until fixed",
                         "It improves significance", "It only matters for paid traffic"], "answer": 1},
            {"q": "Segment analysis is risky because?",
             "options": ["Segments are too small", "Slicing into many subgroups and reporting the 'winning' segment without correction inflates false positives (HARKing risk)",
                         "Segments are not measurable", "Segments are deprecated"], "answer": 1},
            {"q": "Statistical significance does not imply?",
             "options": ["A real effect", "Practical significance — a tiny effect can be statistically significant with enough data, but not worth shipping",
                         "Reliability of the data", "Correct randomization"], "answer": 1},
            {"q": "A pre-registered analysis plan helps because?",
             "options": ["It speeds up implementation", "It commits the team to metrics, segments, and decision rules before seeing results — prevents post-hoc rationalization",
                         "It avoids power calculations", "It guarantees significance"], "answer": 1},
        ]},
        {"module_id": "m_da_biz", "questions": [
            {"q": "Gross margin is calculated as?",
             "options": ["Revenue minus all expenses", "(Revenue − COGS) / Revenue — measures profitability of the core product before overhead",
                         "Revenue ÷ Customers", "Net income ÷ Revenue"], "answer": 1},
            {"q": "Churn rate of 5% monthly implies an annualized churn close to?",
             "options": ["5%", "About 46% — compounding monthly retention of 95% over 12 months",
                         "60%", "Exactly 60%"], "answer": 1},
            {"q": "NPS (Net Promoter Score) is computed by?",
             "options": ["Average rating", "% Promoters (9–10) − % Detractors (0–6); ignores Passives — directional but not statistically rigorous",
                         "Survey response rate", "(Score / 10) × 100"], "answer": 1},
            {"q": "Unit economics' core question is?",
             "options": ["Do we have enough cash?", "Does each unit (customer, transaction, project) generate more value than it costs to acquire and serve — at scale?",
                         "What's our valuation?", "What is the market size?"], "answer": 1},
            {"q": "Why look at contribution margin, not just gross margin?",
             "options": ["Contribution margin includes variable selling costs (e.g. payment processing, support per ticket), giving a truer per-unit profitability picture",
                         "Gross margin is irrelevant", "They are identical", "Contribution margin only matters in retail"], "answer": 0},
        ]},
    ]
    db.seed("quizzes", quizzes)

    print(f"Seeded {len(db.all('users'))} users, {len(db.all('courses'))} courses, "
          f"{len(db.all('modules'))} modules, {len(db.all('quizzes'))} quizzes.")


if __name__ == "__main__":
    seed_data()
